# 创建镜像:
# multipass launch --name master --cpus 2 --mem 2G --disk 10G --cloud-init cloud-config.yaml
# 挂载目录:
# multipass mount ./data master:/home/ubuntu/data

password: 1234asdw
chpasswd: { expire: False }
ssh_pauth: True

apt:
  primary:
    - arches: [default]
      uri: https://mirrors.tuna.tsinghua.edu.cn/ubuntu/

apt_upgrade: true

packages:
  - python3-pip
  - virtualenv
  - nginx
  - nodejs
  - npm
  - yarn

write_files:
  -
    path: /home/ubuntu/test.sh
    content: 'echo "Hello World"'
  -
    path: /home/ubuntu/.pip/pip.conf
    content: "[global]\n# index-url = https://pypi.tuna.tsinghua.edu.cn/simple\nindex-url = https://pypi.doubanio.com/simple/"

runcmd:
  # apt
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -qq update
  - apt-get -qq upgrade
  - apt-get -qq -y autoremove
  # ssh
  - sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config
  - systemctl restart ssh
  # docker
  - curl -fsSL https://get.docker.com | bash -s docker
  - gpasswd -a ubuntu docker
  - systemctl restart docker
  - chmod a+rw /var/run/docker.sock
  - apt install -qq docker-compose

